#!/bin/bash
echo "Doge coin : "
cd ~/bot/dogecoin-1.14.2/bin/
./dogecoin-cli 'getblockcount'
echo "Bitcoin : "
cd ~/bot/bitcoin-0.20.0/bin/
./bitcoin-cli 'getblockcount'
echo "DogeCash : "
cd ~/bot/DogeCash-5.1.1.6rc99/bin/
./dogecash-cli 'getblockcount'
echo "LiteCoin : "
cd ~/bot/litecoin-0.18.1/bin/
./litecoin-cli 'getblockcount'
